services:
  db:
    image: postgres:18
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
      PGDATA: /var/lib/postgresql/18/docker 
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql 
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: your_username
      MINIO_ROOT_PASSWORD: your_password
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - s3_data:/path/to/minio/data:/data

volumes:
  pgdata:
  s3_data:
